INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (3, 0, 4, false, 'Нет, я не боюсь');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (2, 0, 1, false, 'Да, я боюсь');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (1, 0, null, false, 'Вы боитесь технологий?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (4, 1, null, false, 'Вы богаты?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (5, 1, 2, false, 'Да, я богат');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (6, 1, 3, false, 'Нет, я не богат');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (7, 2, null, true, 'Ваш выбор это macOS');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (8, 3, null, true, 'Вы выбор это ChromeOS');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (12, 4, 6, false, 'Для меня важна приватность и безопасность');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (10, 4, 5, false, 'Для меня важна практичность');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (9, 4, null, false, 'Что вы больше предпочитаете: приватность и безопасность или практичность?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (11, 5, null, true, 'Ваш выбор падает на Windows 10/11');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (13, 6, null, false, 'У вас есть личная жизнь и планируете ли вы её?');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (16, 6, 8, false, 'Нет, не планирую');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (14, 6, 7, false, 'Да, есть');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (18, 6, 9, false, 'Нет, но планирую');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (15, 7, null, true, 'Рекомендуется выбрать один из дистрибутивов linux: Ubuntu, Debian, Fedora');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (17, 8, null, true, 'Соберите себе свой дистрибутив линукса с помощью LFS или попробуйте Gentoo');
INSERT INTO public.state_tables (id, num, next_num, is_last, answer) VALUES (19, 9, null, true, 'Стоит выбрать Arch или SlackWare');